// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// gridIDW
NumericVector gridIDW(NumericVector gx, NumericVector gy, NumericVector x, NumericVector y, NumericVector z, double p, double xscale, double yscale, double uncertainty);
RcppExport SEXP _TheSource_gridIDW(SEXP gxSEXP, SEXP gySEXP, SEXP xSEXP, SEXP ySEXP, SEXP zSEXP, SEXP pSEXP, SEXP xscaleSEXP, SEXP yscaleSEXP, SEXP uncertaintySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type gx(gxSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type gy(gySEXP);
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type y(ySEXP);
    Rcpp::traits::input_parameter< NumericVector >::type z(zSEXP);
    Rcpp::traits::input_parameter< double >::type p(pSEXP);
    Rcpp::traits::input_parameter< double >::type xscale(xscaleSEXP);
    Rcpp::traits::input_parameter< double >::type yscale(yscaleSEXP);
    Rcpp::traits::input_parameter< double >::type uncertainty(uncertaintySEXP);
    rcpp_result_gen = Rcpp::wrap(gridIDW(gx, gy, x, y, z, p, xscale, yscale, uncertainty));
    return rcpp_result_gen;
END_RCPP
}
// gridIMW
NumericVector gridIMW(NumericVector gx, NumericVector gy, NumericVector x, NumericVector y, NumericVector z, double p, double xscale, double yscale, double uncertainty);
RcppExport SEXP _TheSource_gridIMW(SEXP gxSEXP, SEXP gySEXP, SEXP xSEXP, SEXP ySEXP, SEXP zSEXP, SEXP pSEXP, SEXP xscaleSEXP, SEXP yscaleSEXP, SEXP uncertaintySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type gx(gxSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type gy(gySEXP);
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type y(ySEXP);
    Rcpp::traits::input_parameter< NumericVector >::type z(zSEXP);
    Rcpp::traits::input_parameter< double >::type p(pSEXP);
    Rcpp::traits::input_parameter< double >::type xscale(xscaleSEXP);
    Rcpp::traits::input_parameter< double >::type yscale(yscaleSEXP);
    Rcpp::traits::input_parameter< double >::type uncertainty(uncertaintySEXP);
    rcpp_result_gen = Rcpp::wrap(gridIMW(gx, gy, x, y, z, p, xscale, yscale, uncertainty));
    return rcpp_result_gen;
END_RCPP
}
// gridNN
NumericVector gridNN(NumericVector gx, NumericVector gy, NumericVector x, NumericVector y, NumericVector z, double p, double xscale, double yscale, double uncertainty);
RcppExport SEXP _TheSource_gridNN(SEXP gxSEXP, SEXP gySEXP, SEXP xSEXP, SEXP ySEXP, SEXP zSEXP, SEXP pSEXP, SEXP xscaleSEXP, SEXP yscaleSEXP, SEXP uncertaintySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type gx(gxSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type gy(gySEXP);
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type y(ySEXP);
    Rcpp::traits::input_parameter< NumericVector >::type z(zSEXP);
    Rcpp::traits::input_parameter< double >::type p(pSEXP);
    Rcpp::traits::input_parameter< double >::type xscale(xscaleSEXP);
    Rcpp::traits::input_parameter< double >::type yscale(yscaleSEXP);
    Rcpp::traits::input_parameter< double >::type uncertainty(uncertaintySEXP);
    rcpp_result_gen = Rcpp::wrap(gridNN(gx, gy, x, y, z, p, xscale, yscale, uncertainty));
    return rcpp_result_gen;
END_RCPP
}
// gridODV
NumericVector gridODV(NumericVector gx, NumericVector gy, NumericVector x, NumericVector y, NumericVector z, double p, double xscale, double yscale, double uncertainty);
RcppExport SEXP _TheSource_gridODV(SEXP gxSEXP, SEXP gySEXP, SEXP xSEXP, SEXP ySEXP, SEXP zSEXP, SEXP pSEXP, SEXP xscaleSEXP, SEXP yscaleSEXP, SEXP uncertaintySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type gx(gxSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type gy(gySEXP);
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type y(ySEXP);
    Rcpp::traits::input_parameter< NumericVector >::type z(zSEXP);
    Rcpp::traits::input_parameter< double >::type p(pSEXP);
    Rcpp::traits::input_parameter< double >::type xscale(xscaleSEXP);
    Rcpp::traits::input_parameter< double >::type yscale(yscaleSEXP);
    Rcpp::traits::input_parameter< double >::type uncertainty(uncertaintySEXP);
    rcpp_result_gen = Rcpp::wrap(gridODV(gx, gy, x, y, z, p, xscale, yscale, uncertainty));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_TheSource_gridIDW", (DL_FUNC) &_TheSource_gridIDW, 9},
    {"_TheSource_gridIMW", (DL_FUNC) &_TheSource_gridIMW, 9},
    {"_TheSource_gridNN", (DL_FUNC) &_TheSource_gridNN, 9},
    {"_TheSource_gridODV", (DL_FUNC) &_TheSource_gridODV, 9},
    {NULL, NULL, 0}
};

RcppExport void R_init_TheSource(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
