# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Inverse Distance Gridding
#'
#' @export
gridIDW <- function(gx, gy, x, y, z, p, xscale, yscale, uncertainty) {
    .Call('_TheSource_gridIDW', PACKAGE = 'TheSource', gx, gy, x, y, z, p, xscale, yscale, uncertainty)
}

#' Inverse Metropolis-distance Gridding
#'
#' @export
gridIMW <- function(gx, gy, x, y, z, p, xscale, yscale, uncertainty) {
    .Call('_TheSource_gridIMW', PACKAGE = 'TheSource', gx, gy, x, y, z, p, xscale, yscale, uncertainty)
}

#' Nearest Neighbor Gridding
#'
#' @export
gridNN <- function(gx, gy, x, y, z, p, xscale, yscale, uncertainty) {
    .Call('_TheSource_gridNN', PACKAGE = 'TheSource', gx, gy, x, y, z, p, xscale, yscale, uncertainty)
}

#' Inverse Distance Gridding (as in ODV)
#'
#' @export
gridODV <- function(gx, gy, x, y, z, p, xscale, yscale, uncertainty) {
    .Call('_TheSource_gridODV', PACKAGE = 'TheSource', gx, gy, x, y, z, p, xscale, yscale, uncertainty)
}

