# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

gridIDW <- function(gx, gy, x, y, z, p, xscale, yscale, uncertainty) {
    .Call('_TheSource_gridIDW', PACKAGE = 'TheSource', gx, gy, x, y, z, p, xscale, yscale, uncertainty)
}

gridODV <- function(gx, gy, x, y, z, p, xscale, yscale, uncertainty) {
    .Call('_TheSource_gridODV', PACKAGE = 'TheSource', gx, gy, x, y, z, p, xscale, yscale, uncertainty)
}

